const projects = {
    pt: [
        {
            icon: "📋",
            name: "TaskForge",
            shortDesc: "Plataforma de gerenciamento de projetos com autenticação robusta e Kanban customizável.",
            fullDesc: "Plataforma de gerenciamento de projetos full stack construída com arquitetura DDD (Domain-Driven Design). Inclui autenticação robusta com JWT, OAuth 2.0 e 2FA, boards Kanban customizáveis, notificações em tempo real e dashboards de produtividade. Desenvolvida com foco em escalabilidade e segurança de dados.",
            tags: ["Node.js", "TypeScript", "Vue 3", "PostgreSQL", "Prisma", "JWT", "OAuth", "2FA"],
            github: "https://github.com/Renan-Sena",
            live: null,
            imgPlaceholder: "https://my-portfolio-eight-iota-22.vercel.app/assets/Manual da marca TaskFoge (1200 x 630 px).svg",
        },
        {
            icon: "🥋",
            name: "Judo Grip Tracker",
            shortDesc: "Sistema de visão computacional para rastreamento de pegadas em vídeos de judô.",
            fullDesc: "Sistema de visão computacional que detecta e rastreia pegadas de atletas em vídeos de judô em tempo real. Utiliza MediaPipe para detecção de pose e Filtro de Kalman para suavização de trajetória. Gera relatórios automáticos de padrões táticos e estatísticas de combate para treinadores.",
            tags: ["Python", "OpenCV", "MediaPipe", "Kalman Filter", "NumPy", "Computer Vision"],
            github: "https://github.com/Renan-Sena",
            live: null,
            imgPlaceholder: "🥋",
        },
        {
            icon: "🏦",
            name: "Banking Module",
            shortDesc: "Módulo bancário com criptografia AES-256-GCM e automação de processos internos.",
            fullDesc: "Módulo bancário de alta segurança com foco em proteção de dados sensíveis. Implementa criptografia AES-256-GCM para transações, auditoria de logs em tempo real, automação de processos internos com scripts Python e Node.js, integração com APIs de pagamento e conformidade com regulamentações bancárias.",
            tags: ["Node.js", "TypeScript", "Python", "AES-256-GCM", "PostgreSQL", "REST API"],
            github: "https://github.com/Renan-Sena",
            live: null,
            imgPlaceholder: "🏦",
        },
        {
            icon: "🚗",
            name: "Automotive Platform",
            shortDesc: "Plataforma web para o setor automotivo com suporte a sistemas legados.",
            fullDesc: "Aplicação web completa para o setor automotivo focada em manutenção de sistemas legados, otimização de performance e suporte técnico especializado. Inclui migração gradual para Vue.js, refatoração de módulos críticos, implementação de testes automatizados e monitoramento de performance em produção.",
            tags: ["TypeScript", "Vue.js", "Node.js", "PostgreSQL", "Jest", "Legacy Migration"],
            github: "https://github.com/Renan-Sena",
            live: null,
            imgPlaceholder: "🚗",
        },
    ],
    en: [
        {
            icon: "📋",
            name: "TaskForge",
            shortDesc: "Project management platform with robust auth and customizable Kanban boards.",
            fullDesc: "Full stack project management platform built with DDD (Domain-Driven Design) architecture. Features robust authentication with JWT, OAuth 2.0 and 2FA, customizable Kanban boards, real-time notifications and productivity dashboards. Built with a focus on scalability and data security.",
            tags: ["Node.js", "TypeScript", "Vue 3", "PostgreSQL", "Prisma", "JWT", "OAuth", "2FA"],
            github: "https://github.com/Renan-Sena",
            live: null,
            imgPlaceholder: "📋",
        },
        {
            icon: "🥋",
            name: "Judo Grip Tracker",
            shortDesc: "Computer vision system for grip tracking in judo match videos.",
            fullDesc: "Computer vision system that detects and tracks athlete grips in judo videos in real time. Uses MediaPipe for pose detection and Kalman Filter for trajectory smoothing. Automatically generates reports on tactical patterns and combat statistics for coaches.",
            tags: ["Python", "OpenCV", "MediaPipe", "Kalman Filter", "NumPy", "Computer Vision"],
            github: "https://github.com/Renan-Sena",
            live: null,
            imgPlaceholder: "🥋",
        },
        {
            icon: "🏦",
            name: "Banking Module",
            shortDesc: "Banking module with AES-256-GCM encryption and internal process automation.",
            fullDesc: "High-security banking module focused on sensitive data protection. Implements AES-256-GCM encryption for transactions, real-time audit logging, internal process automation with Python and Node.js scripts, payment API integration and banking regulatory compliance.",
            tags: ["Node.js", "TypeScript", "Python", "AES-256-GCM", "PostgreSQL", "REST API"],
            github: "https://github.com/Renan-Sena",
            live: null,
            imgPlaceholder: "🏦",
        },
        {
            icon: "🚗",
            name: "Automotive Platform",
            shortDesc: "Web application for the automotive sector with legacy system support.",
            fullDesc: "Complete web application for the automotive sector focused on legacy system maintenance, performance optimization and specialized technical support. Includes gradual migration to Vue.js, refactoring of critical modules, automated testing implementation and production performance monitoring.",
            tags: ["TypeScript", "Vue.js", "Node.js", "PostgreSQL", "Jest", "Legacy Migration"],
            github: "https://github.com/Renan-Sena",
            live: null,
            imgPlaceholder: "🚗",
        },
    ]
};